spring:
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
    redis:
      cache-null-values: false
      time-to-live: 300s


kakao:
  url: https://dapi.kakao.com/v2/search/blog
  ak: KakaoAK 9c50c6b8ca4cde7a8acdd39b5370998b

naver:
  url: https://openapi.naver.com/v1/search/blog.json
  clientId: LnQQAcTupOqyCQSfZhRk
  clientSecret: QrfmWxMfRX
